/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserDashboardImport } from './routes/user/dashboard'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const AuthTeacherLazyImport = createFileRoute('/auth/teacher')()
const AuthStudentLazyImport = createFileRoute('/auth/student')()
const AuthRoleLazyImport = createFileRoute('/auth/role')()
const AuthAccountsSignupLazyImport = createFileRoute('/auth/accounts/signup')()
const AuthAccountsSigninLazyImport = createFileRoute('/auth/accounts/signin')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthTeacherLazyRoute = AuthTeacherLazyImport.update({
  id: '/auth/teacher',
  path: '/auth/teacher',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/teacher.lazy').then((d) => d.Route))

const AuthStudentLazyRoute = AuthStudentLazyImport.update({
  id: '/auth/student',
  path: '/auth/student',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/student.lazy').then((d) => d.Route))

const AuthRoleLazyRoute = AuthRoleLazyImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/role.lazy').then((d) => d.Route))

const UserDashboardRoute = UserDashboardImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AuthAccountsSignupLazyRoute = AuthAccountsSignupLazyImport.update({
  id: '/auth/accounts/signup',
  path: '/auth/accounts/signup',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/accounts/signup.lazy').then((d) => d.Route),
)

const AuthAccountsSigninLazyRoute = AuthAccountsSigninLazyImport.update({
  id: '/auth/accounts/signin',
  path: '/auth/accounts/signin',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/accounts/signin.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardImport
      parentRoute: typeof rootRoute
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/auth/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/teacher': {
      id: '/auth/teacher'
      path: '/auth/teacher'
      fullPath: '/auth/teacher'
      preLoaderRoute: typeof AuthTeacherLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/accounts/signin': {
      id: '/auth/accounts/signin'
      path: '/auth/accounts/signin'
      fullPath: '/auth/accounts/signin'
      preLoaderRoute: typeof AuthAccountsSigninLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/accounts/signup': {
      id: '/auth/accounts/signup'
      path: '/auth/accounts/signup'
      fullPath: '/auth/accounts/signup'
      preLoaderRoute: typeof AuthAccountsSignupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/role': typeof AuthRoleLazyRoute
  '/auth/student': typeof AuthStudentLazyRoute
  '/auth/teacher': typeof AuthTeacherLazyRoute
  '/auth/accounts/signin': typeof AuthAccountsSigninLazyRoute
  '/auth/accounts/signup': typeof AuthAccountsSignupLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/role': typeof AuthRoleLazyRoute
  '/auth/student': typeof AuthStudentLazyRoute
  '/auth/teacher': typeof AuthTeacherLazyRoute
  '/auth/accounts/signin': typeof AuthAccountsSigninLazyRoute
  '/auth/accounts/signup': typeof AuthAccountsSignupLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/auth/role': typeof AuthRoleLazyRoute
  '/auth/student': typeof AuthStudentLazyRoute
  '/auth/teacher': typeof AuthTeacherLazyRoute
  '/auth/accounts/signin': typeof AuthAccountsSigninLazyRoute
  '/auth/accounts/signup': typeof AuthAccountsSignupLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user/dashboard'
    | '/auth/role'
    | '/auth/student'
    | '/auth/teacher'
    | '/auth/accounts/signin'
    | '/auth/accounts/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/user/dashboard'
    | '/auth/role'
    | '/auth/student'
    | '/auth/teacher'
    | '/auth/accounts/signin'
    | '/auth/accounts/signup'
  id:
    | '__root__'
    | '/'
    | '/user/dashboard'
    | '/auth/role'
    | '/auth/student'
    | '/auth/teacher'
    | '/auth/accounts/signin'
    | '/auth/accounts/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  UserDashboardRoute: typeof UserDashboardRoute
  AuthRoleLazyRoute: typeof AuthRoleLazyRoute
  AuthStudentLazyRoute: typeof AuthStudentLazyRoute
  AuthTeacherLazyRoute: typeof AuthTeacherLazyRoute
  AuthAccountsSigninLazyRoute: typeof AuthAccountsSigninLazyRoute
  AuthAccountsSignupLazyRoute: typeof AuthAccountsSignupLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  UserDashboardRoute: UserDashboardRoute,
  AuthRoleLazyRoute: AuthRoleLazyRoute,
  AuthStudentLazyRoute: AuthStudentLazyRoute,
  AuthTeacherLazyRoute: AuthTeacherLazyRoute,
  AuthAccountsSigninLazyRoute: AuthAccountsSigninLazyRoute,
  AuthAccountsSignupLazyRoute: AuthAccountsSignupLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/user/dashboard",
        "/auth/role",
        "/auth/student",
        "/auth/teacher",
        "/auth/accounts/signin",
        "/auth/accounts/signup"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/user/dashboard": {
      "filePath": "user/dashboard.tsx"
    },
    "/auth/role": {
      "filePath": "auth/role.lazy.tsx"
    },
    "/auth/student": {
      "filePath": "auth/student.lazy.tsx"
    },
    "/auth/teacher": {
      "filePath": "auth/teacher.lazy.tsx"
    },
    "/auth/accounts/signin": {
      "filePath": "auth/accounts/signin.lazy.tsx"
    },
    "/auth/accounts/signup": {
      "filePath": "auth/accounts/signup.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
